cogs/emoji.resize: revert changes in 02c773e03d83c6804f3061ab87d886e02ded2af4
there were errors occuring when the bot resized images more than once.
MissingDelegateError: no decode delegate for this image format `' @ error/blob.c/BlobToImage/361
at `image = Image(blob=image_data)`.
This fixes that.